ECHO off
:: Usage: call BuileNumber_Increment.cmd ..\buildnumber.h
:: D.Giandomenico 6/2011
:: The first argument, %1, should contain the target header file.
SET TARGET_BUILDNUMBER_HEADERFILE=%1

:: Increment the build number.
:: Reads the build number from a one line DOS command called getBuildNumber,
:: then increments the number, and rewrites the DOS command.

:: Read %buildnumber%;  This file is where the buildnumber is incremented and stored.
CALL BuildNumber_Get.cmd

:: write the header file
ECHO //This file is automatically generated by LRT's build script. > %TARGET_BUILDNUMBER_HEADERFILE%
ECHO #define kBuildNumber %buildnumber% >> %TARGET_BUILDNUMBER_HEADERFILE%

:: Increment the buildnumber
ECHO SET /A buildnumber=%buildnumber%+1 > BuildNumber_Get.cmd

:: Diagnostic result
TYPE %TARGET_BUILDNUMBER_HEADERFILE%